resources:

- name: repo
  type: git
  source:
    uri: https://github.com/emerald-squad/artifactory-resource.git
    branch: master
    ignore_paths:
    - README.md
    - ci/**

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:emerald-squad/artifactory-resource.git
    branch: 'version'
    file: version
    private_key: ((github-key))

- name: docker-hub
  type: docker-image
  source:
    repository: emeraldsquad/artifactory-resource
    username: ((docker-hub-username))
    password: ((docker-hub-password))

jobs:

- name: prerelease-tag
  serial: true
  serial_groups: [docker-push]
  plan:
  - in_parallel:
    - get: repo
    - put: version-rc
      resource: version
      params:
        pre: rc
  - put: docker-hub
    params:
      build: repo
      tag_file: version-rc/version
      tag_as_latest: false

- name: release-tag
  serial: true
  serial_groups: [docker-push]
  plan:
  - in_parallel:
    - get: docker-hub
      passed: [prerelease-tag]
      params:
        save: true
    - put: version
      params:
        bump: final
  - put: docker-hub
    params:
      load: docker-hub
      tag_file: version/version
      tag_as_latest: true
  - put: bump-patch
    resource: version
    params:
      bump: patch

- name: bump-major
  plan:
  - put: version
    params:
      bump: major

- name: bump-minor
  plan:
  - put: version
    params:
      bump: minor

- name: bump-patch
  plan:
  - put: version
    params:
      bump: patch

groups:

- name: publish-image
  jobs:
  - prerelease-tag
  - release-tag
  
- name: bump-version
  jobs:
  - bump-major
  - bump-minor
  - bump-patch
